# Generated by Django 4.1 on 2024-04-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedDataset',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('dataset_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('childes_db_version', models.CharField(max_length=255)),
                ('dataset_version', models.CharField(max_length=255)),
                ('coding_table', models.CharField(max_length=255)),
                ('tag_type', models.CharField(max_length=255)),
                ('model_version', models.CharField(max_length=255)),
                ('date_of_release', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('citation', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'derived_datasets',
            },
        ),
        migrations.CreateModel(
            name='speech_acts_crf_record',
            fields=[
                ('utterance_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('speech_act', models.CharField(choices=[['QN', 'Ask a product-question (wh-question'], ['SA', 'Answer a wh-question with a statement']], default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'speech_acts_crf',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('variable_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data_type', models.JSONField()),
            ],
            options={
                'db_table': 'variables',
            },
        ),
        migrations.CreateModel(
            name='VariableMapping',
            fields=[
                ('mapping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_id', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, to='db.deriveddataset')),
                ('variable_name', models.ForeignKey(db_column='variable_name', on_delete=django.db.models.deletion.CASCADE, to='db.variable')),
            ],
            options={
                'db_table': 'variable_mappings',
            },
        ),
    ]
